spring:
  config:
    import: classpath:application-infra.yml
  main:
    web-application-type: none
  profiles:
    default: supabase
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=2000,expireAfterWrite=60s

logging:
  config: classpath:logback-spring.xml
