services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=sigla'
      - 'POSTGRES_PASSWORD=sigla'
      - 'POSTGRES_USER=sigla'
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U sigla -d sigla']
      interval: 5s
      timeout: 5s
      retries: 10
